### ISSUE TITLE
Null pointer can not be passed to free in C

### ISSUE THREAD

**Issue by wandernauta** [utwente-fmt/vercors#1240]
The following C program does not verify, giving as reason that the pointer p may be NULL:

```
#include <stdlib.h>

int main() {
    int* p = NULL;
    free(p);
}
```

This is unexpected as the program is fine: passing NULL to the `free` function is [allowed](https://en.cppreference.com/w/c/memory/free); it is defined to have no effect. In other words, the argument should either be a valid pointer or NULL.

**Comment by superaxander** [comment]
Indeed we currently do not keep track of the origin of pointers. We should look at how other verifiers do this.

For example in VeriFast you can have:
```c
#include <stdlib.h>

void foo(int a) 
//@ requires true;
//@ ensures true;
{}

void test(int *a)
//@ requires integer(a, _) &*& malloc_block_ints(a, 1);
//@ ensures true;
{
    foo(*a);
    free(a);
}
```
where `integer(a, _)` matches our `Perm(a, write)` and `malloc_block_ints(a, n)` is a predicate inhaled whenever `malloc` is called to create a pointer to `n` integers. 

In ACSL (Frama-C) there are separate allocation clauses to describe the behaviour of a function as described in the [ACSL Manual](https://frama-c.com/download/acsl-1.20.pdf) paragraph 2.7.3:

> – `\allocable{L}(p)` holds if and only if the pointer `p` refers, at the label `L`, to the base address of an unallocated memory block.
> ```
> \allocable{id} : void* → boolean
> ```
> For any pointer `p` and label `L`
> ```
> \allocable{L}(p) <==> (\allocation{L}(p)==\unallocated && (void*)p==(void*)\base_addr{L}(p))
> ```
> – `\freeable{L}(p)` holds if and only if the pointer `p` refers, at the label `L`, to the base address of an allocated memory block that can be safely released using the C function free. Note that `\freeable(\null)` does not hold, despite `NULL` being a valid argument to the C function free.
> ```
> \freeable{id} : void* → boolean
> ```
> For any pointer `p` and label `L`
> ```
> \freeable{L}(p) <==> (\allocation{L}(p)==\dynamic && (void*)p==(void*)\base_addr{L}(p))
> ```

I think I would prefer the simplicity of the VeriFast approach here. I don't think we'd have much benefit from keeping track of whether certain addresses are "allocable" since we don't reason about addresses anyway. (Frama-C basically just keeps track of a map from addresses to values to implement their pointers whereas we use Viper's fields)

**Comment by bobismijnnaam** [comment]
From a soundness perspective, rejecting a correct program is not a problem. It's also nice that the contract of free is not conditional, i.e. supporting null would introduce a branch. That said, I agree it would be nice to handle this case as well. Probably the additional branch would not influence verification significantly.
