### ISSUE TITLE
Instability of Travis

### ISSUE THREAD

**Issue by wytseoortwijn** [utwente-fmt/vercors#143]
Continuous integration with Travis has become unstable after #120. For some reason, more-or-less random example cases seem to fail in the Travis environment (usually only one or two examples). There was some hope that a new Viper update would make Travis stable again, but this is not the case (see #142).

**Comment by wytseoortwijn** [comment]
Updating Scala to version 2.12.7 and the JDK to OracleJDK9 (or higher) doesn't seem to have any influence on the random failures.

**Comment by Sophietje** [comment]
The following test cases fail:
- SummationKernel1 (examples/carp/summation-kernel-1.pvl)
- JavaArrayExamples (examples/arrays/JavaArrayExamples.java)
- OpenMPSectionReduced (examples/openmp/sections-reduced.c)

The test cases that fail produce an "java.util.concurrent.ExecutionException: caused by a NullPointerException". Specifically it says that the cause is "z3.interaction.failed" because a pure virtual method is called. This error (the virtual method one) can occur when you try to make a call on an object that has already been deleted or when the object has not fully been constructed yet.

I was unable to reproduce the error on my computer, on a VM, or on a VM in a Docker environment.
Allocating a larger heap did not solve the problem. Nor did there seem to be any insufficient memory problems.

For now we can use a workaround by asking Travis to set up a MacOS environment instead of an Ubuntu one. The test cases seem to succeed in this OSX environment.

**Comment by niomaster** [comment]
For posterity: the root cause was a race condition in the implementation of locks for linux in an older version of z3. This has since been fixed by updating z3 a few months back.
