### ISSUE TITLE
sequence translation into silver

### ISSUE THREAD

**Issue by Safari1991** [utwente-fmt/vercors#149]
There is a bug in translation into silver when we use tail() function with concatenation of two sequences. For example this expression
assert tail(xs) + ys == tail(xs + ys)

is translated in silver in this way:
assert xs[1..] ++ ys == xs ++ ys[1..]

which the correct form is
assert xs[1..] ++ ys == (xs ++ ys)[1..]
(adding extra parentheses around xs ++ ys)

**Comment by wytseoortwijn** [comment]
@Safari1991 This is basically because the expression parser is a mess. Expressions like `\old(xs)[1]` or `(xs + ys)[0]` also don't parse. In this case, the parser doesn't seem to correctly handle parentheses.

I think someone should simply make a thorough pass over the parser. That would (indirectly) fix this.

**Comment by wytseoortwijn** [comment]
@niomaster I see. But apart from the printing, do things still go wrong? If VerCors correctly translates this, shouldn't it just work then?

**Comment by niomaster** [comment]
it does just work, you can prove the first assertion in vercors just fine (given |xs|>0).

**Comment by niomaster** [comment]
Also I think it's just the PVL expression parser that's quite messy, and the case you refer to is silver. I'll fix that one soon, though :)

**Comment by niomaster** [comment]
Closing as it's out of our tool
