### ISSUE TITLE
Method calls do not work in if conditions

### ISSUE THREAD

**Issue by bobismijnnaam** [utwente-fmt/vercors#189]
Using method calls as in the following snippet gives an error, where I would (naively) expect it to be supported:

```
class MyClass {
  int bar() { return 0; }

  void foo() {
    if (bar() == bar()) {}
  }
}
```

Error:

```
Plain bar
Plain foo
Parsed 1 file(s) in: 152ms
Comparing Integer with 0 as Integer
Comparing Integer with 0 as Integer
Comparing Integer with 0 as Integer
Comparing Ref with new () as Ref
At file if-issue.pvl from line 5 column 9 until line 5 column 13: unexpected invokation of non-void method method_MyClass_bar at file if-issue.pvl from line 5 column 9 until line 5 column 13
Triggered by file if-issue.pvl from line 5 column 9 until line 5 column 13:
The final verdict is Error
entire run took 885 ms
```

As pointed out by Pieter, maybe this is because expressions with side effects are not allowed? In that case an error could be printed explaining the side effect restriction, or maybe it could be documented in the wiki.

**Comment by niomaster** [comment]
A later pass expects the method calls to be flattened out of the if condition, but Flatten explicitly copies branch conditions instead of flattening them, probably because the expression is not always fully evaluated, e.g.:


```
if(cond1) {
} else if(cond2) {
}
```

`cond2` is only evaluated when `cond1` is false. I would suggest rewriting the above to:

```
if(cond1) {
} else {
  if(cond2) {
  }
}
```

Which in turn can be flattened to:

```
flatten1 = cond1
if(flatten1) {
} else {
  flatten2 = cond2
  if(flatten2) {
  }
}
