### ISSUE TITLE
Pure function calls inside invariants

### ISSUE THREAD

**Issue by wytseoortwijn** [utwente-fmt/vercors#217]
The following code snippet exhibits a bug in VerCors:

```java
class Foo {
  invariant xs != null;
  requires (\forall* int i; 0 <= i && i < xs.length; Perm(xs[i], 1/2));
  ensures \result;
  pure boolean f(int[] xs);

  invariant xs != null;
  requires (\forall* int i; 0 <= i && i < xs.length; Perm(xs[i], 1));
  void bar(int[] xs) {
    invariant inv((\forall* int i; 0 <= i && i < xs.length; Perm(xs[i], 1/2)) ** f(xs))
    {
      par (int tid = 0 .. xs.length)
        context Perm(xs[tid], 1/2);
      {
        atomic(inv) { } // problem is here
      }
    }
  }
}
```

Inside the `invariant` is a function call `f(xs)`, with `xs` an integer array. The function `f` requires read permission for each entry in `xs`. This causes VerCors to crash, due to a problem in `atomic(inv) { }`. More specifically, VerCors gives:

```
class Foo
  method f is final
    initial declaration
  method bar is final
    initial declaration
  method Foo is final
    initial declaration
=== ./examples/test/test25.pvl     ===
  11 		
  12 		invariant inv(
                                                                      [-----
  13 			(\forall* int i; 0 <= i && i < xs.length; Perm(xs[i], 1/2)) ** f(xs)
                                                                       -----]
  14 		)
  15 		{
-----------------------------------------
  Local name globals is undefined
=========================================
At file ./examples/test/test25.pvl from line 13 column 67 until line 13 column 71: fatal error
Triggered by file ./examples/test/test25.pvl from line 13 column 67 until line 13 column 71:
The final verdict is Error
entire run took 990 ms
```

This has something to do with permissions I think. If `f` does not require any permissions, everything goes well.

**Comment by sjcjoosten** [comment]
Related to #194. Did #201 fix this? (Can someone test this again and close if it doesn't reproduce)

**Comment by Sophietje** [comment]
I pulled the newest version of VerCors and ran it on the example above. It still gives me an error, though it is a different error this time.

```
=== ../../VerCors-Examples/20190718-testIssue217.pvl ===
   8   requires (\forall* int i; 0 <= i && i < xs.length; Perm(xs[i], 1));
   9   void bar(int[] xs) {
                                                                                     [-----
  10     invariant inv((\forall* int i; 0 <= i && i < xs.length; Perm(xs[i], 1/2)) ** f(xs))
                                                                                      -----]
  11     {
  12       par (int tid = 0 .. xs.length)
-----------------------------------------
  Local name globals is undefined
=========================================
At file ../../VerCors-Examples/20190718-testIssue217.pvl from line 10 column 82 until line 10 column 86: fatal error
```

**Comment by niomaster** [comment]
Still reproducible. The problem is:
* The thread contract is checked by putting it in a new method
* The variables it needs are determined by the free variables in the par body
* The body is rewritten *after* determining the free variables
* This goes wrong, because the same pass flattens the atomic and inlines the invariant, in which a new variable occurs (globals in this case, which is just some internal variable)

Here is a smaller example:

```
class InvariantUse {
    void test() {
        boolean b;
        invariant inv(b) {
            par(int tid = 0..2) {
                atomic(inv){}
            }
        }
    }
}
```

**Comment by bobismijnnaam** [comment]
On a related note, the following also verifies:

```
class InvariantUse {
    void test() {
        boolean b;
        b = true;
        invariant inv(b) {
          b = false;
          atomic(inv) {
            assert b == true && b == false;
          }
        }
    }
}
```

Should we maybe forbid using local variables in an invariant, or something similar/more intricate?

**Comment by niomaster** [comment]
Ah yes, so really the current way of inlining (it generates `inhale b` or so) is also wrong. I also think that the rewrite-after-free_vars is still wrong, because it's fine to introduce new names that are immutable (i.e. arguments such as globals).

**Comment by bobismijnnaam** [comment]
As Pieter is reworking the ParallelBlockEncoder, we discussed the current semantics of invariant and barriers yesterday, and if they need to change/improve.

The current semantics are as follows. invariant/atomic is currently modeled as an inhale/exhale of the unmodified expression in the invariant. This causes unsoundness when stack vars are used, as they can be changed inbetween establishing the invariant and invoking atomic. Additionally, since a barrier synchronizes all threads, any previously established invariant can be used to prove the barrier contract, as long as the barrier maintains each invariant. This is similar to how barriers work in Amighi's PhD thesis, where a local barrier gets access to the local invariant, and a global barrier to the global invariant [[Amighi]].

To fix the unsoundess, we propose to copy any stack variables to anonymous variables on the stack, and then use these anonymous variables in the invariant. Semantically, this takes a snapshot of the stack when the invariant is established. Combined with the self-framing property of heap vars, this should make invariants sound again, while still allowing specification of state in relation to state on the stack.

For the invariant/barrier interaction we do not have a concrete proposal. It also does not seem directly unsound (but maybe I missed an example). However we think the situation could be improved, as using all invariants in a barrier by default might not be optimal. The primary observation is that an invariant is almost always used in combination with a par block. Therefore, it could be useful to require an invariant to be defined at a par block. Then, when invariants are scoped per par block, barriers can specify on which invariant(s) a barrier is needed. The invariants that are mentioned in the barrier can be used for proving the barrier contract. This mechanism can be used to model 1) several threads that have access to two distinct locks, or 2) a hierarchy of threads of two levels, where the threads have access to a local and a global invariant.

[Amighi]: https://doi.org/10.3990/1.9789036544399

**Comment by bobismijnnaam** [comment]
After some discussion we found another example of confusing behavior with the above proposed snapshot semantics:

```java
int[] xs = new int[1];
int[] old_xs_ghost = xs; // To save the old value of xs 
int[] new_xs_ghost; // To refer to the new value of xs later on

invariant inv(Perm(xs[0], write)) {
  assert Perm(xs[0], write); // Fails as expected

  atomic(inv) {
    xs[0] = 10; // Ok
    xs = new int[1]; // Ok
    new_xs_ghost = xs; // Save the new value
    assert xs == new_xs_ghost;
    assert old_xs_ghost != new_xs_ghost
    
    // This works because we just allocated, not because of the invariant
    assert Perm(xs[0], write); 

    // Also still works, because we have not left atomic
    assert Perm(old_xs_ghost[0], write);
  }

  // Strangely enough, even though we are not in an atomic:
  assert Perm(new_xs_ghost[0], write);
  assert Perm(xs[0], write);

  // Effectively, the invariant is now managing permissions for a reference 
  // we cannot name anymore. For example:

  boolean b = true;
  while (b) {
    atomic (inv) {
      // The following does not hold, because xs != old_xs_ghost
      // And inv contains permission for old_xs_ghost!
      assert Perm(xs[0], write); // Fails
      // Permissions for new_xs_ghost also do not propagate into the loop
      // because any permissions must be mentioned in the loop invariant
      assert Perm(new_xs_ghost[0], write); // Fails
      // We only get perm for the old one:
      assert Perm(old_xs_ghost[0], write); // Fails
    }
    b = false;
  }
}
```

In a nutshell:

1. The current stack frame always has write permission to stack variables
2. By using a stack variable in an invariant, implicitly a read permission is given to the invariant
3. `write` + `read` > `write`, and hence this leads to unsoundness.

There are at least three solutions:

1. Disallow stack variables in invariant. This implies any used variable used in the invariant must be on the heap, i.e. reached via `this`.
2. Only allow stack vars in invariant that are `final`. This could be improved by also allowing effectively `final`, i.e. variables that are only written to to within the invariant.
3. Introduce perms for stack variables.

Option 1 and 2 seem the most straightforward to implement currently. They would also work for most practical examples, as whenever a stack variable appears in an invariant, it often does not change. Admittedly, this argument also suggests the snapshot semantics are not problematic at all. But they would still be confusing for newcomers. Option 3 could be interesting, as it is similar to the semantics used in the C frontend, but needs some more thinking to integrate in Java.
