### ISSUE TITLE
Generated identity function

### ISSUE THREAD

**Issue by wytseoortwijn** [utwente-fmt/vercors#239]
VerCors seems to generate/add an identity function to every Viper file it produces (at least in my older, late 2018 version, it does):
```java
function id(x: Int): Int 
{
  x
}
```
However, I notices that this function sometimes makes verification harder. For example, in my version of VerCors, the following code snippet does not verify, and this is only because the `id` function is being used:
```java
invariant a != null;
invariant a.length % 2 == 0;
context (\forall* int j; 0 <= j && j < a.length; Perm(a[j], write));
void zeroall(int[] a) {
  par (int tid = 0 .. a.length/2)
    context Perm(a[2 * tid], write);
    ensures a[2 * tid] == 0;
  {
    a[2 * tid] = 0;             
  }
}
```

Could we get rid of `id`, or make it into a macro, instead of a function, so that Viper can easily eliminate it?

**Comment by Sophietje** [comment]
In the newest version of VerCors the problematic identity function is no longer generated.

When searching through the history, the first commit where the id function is no longer generated is the following: https://github.com/utwente-fmt/vercors/commit/ea54ccf777e3cd8d5d3c37595ccb8fa2be958253. Thus it seems to be resolved due to the new condition in the if-statement in the AbstractTypeCheck?

**Comment by niomaster** [comment]
My best guess is that that change in AbstractTypeCheck breaks some detection in RecognizeMultiDim, which is one of the very few places where an `Identity` is created. I propose we remove `Identity` altogether.

**Comment by raulmonti** [comment]
Since it is making verification harder, and no one has been able to find why it is needed I suggest to remove the operator to avoid having the problem again.
