### ISSUE TITLE
Using submodules instead of cloning files

### ISSUE THREAD

**Issue by sjcjoosten** [utwente-fmt/vercors#262]
On https://github.com/utwente-fmt/vercors/tree/master/vercors/viper
the folders silicon, carbon and silver should become submodules (pinned to the right version). This will prevent people from accidentally changing those files in the future.

**Comment by niomaster** [comment]
Git submodules have some drawbacks. The repo's we need to include (silver, silicon, carbon) are mercurial repos. We could all install the git-hg plugin, but this doesn't seem well-supported anymore (can't find it in the Ubuntu repositories for 18.04 for example). Also, this requires us to install yet another tool to even build vercors.

The option I'm currently exploring is specifying the git repository as a dependency in the sbt build file of viper_api. This means the viper files no longer need to be in the repository, but sbt fetches them for us instead. This works great, except that carbon and silicon expect a symlink to silver in their directory. I tried creating those programatically after updating, but I can't convince sbt that the three projects (silver, silicon/silver, carbon/silver) are the same project, so they try to build silver concurrently in the same location.

However, what does work is editing carbon/build.sbt and silicon/build.sbt to refer to the git repository of silver instead. Currently I think the best option is to maintain a one-line patch for carbon and silicon that is applied automatically on update, that changes `(project in file("silver"))` to `ProjectRef(uri("hg:https://bitbucket.org/viperproject/silver#commitish"), "silver")`. It looks like `patch` is usually available by default on both linux and windows, so that solves the issue of cross-platform symlinks as well.

**Comment by sjcjoosten** [comment]
The aim is to not have our repo free of files that we should not change. I think the patch solution is a good option.
