### ISSUE TITLE
The build should output no warnings

### ISSUE THREAD

**Issue by niomaster** [utwente-fmt/vercors#275]
There's a few parts to this. I think it's best to disable warnings for the viper projects completely, as we have decided not to patch them. For the vercors project, we should decide which warnings we solve, and which we should ignore, but we should make that explicit somehow (is there a `@SuppressWarnings` in scala?).

**Comment by Sophietje** [comment]
I had a look but there seems to be no equivalent construct in Scala. 
On SO (https://stackoverflow.com/questions/47894596/scala-actually-suppress-compiler-warnings) they mention that you can either disable a warning entirely (on the whole project instead of a specific part of the project) or use a plugin called silencer (https://github.com/ghik/silencer)

**Comment by niomaster** [comment]
I guess we should at least solve all the warnings in our scala source then :+1:
