### ISSUE TITLE
Fractions compile to integer and you get type error

### ISSUE THREAD

**Issue by raulmonti** [utwente-fmt/vercors#277]
The following example is not working right:
```
given frac p;
invariant 1/5 < p && p < 1/2;
```
The important part of the error message is:
```
[debug] At Main.java:634: 
[debug] java.lang.AssertionError: assertion failed: Expected both operands to be of the same sort, but found Int (1 / 5) and Perm (p@12@03).
[debug] At Main.java:634: 
[debug] 	at scala.Predef$.assert(Predef.scala:219)
[debug] At Main.java:634: 
[debug] 	at viper.silicon.state.terms.Less.<init>(Terms.scala:845)
[debug] At Main.java:634: 
[debug] 	at viper.silicon.state.terms.Less$.apply(Terms.scala:854)
[debug] At Main.java:634: 
[debug] 	at viper.silicon.state.terms.Less$.apply(Terms.scala:850)
```
Furthermore, when I use --compiled option I find that it translates the second line to:
`invariant 1 \ 5 < p && p < 1 \ 2
`
It writes `\` instead of `/`. We may need to check if we are doing something wrong there or if it is viper's printing what is going wrong.
One more thing that I found inconvenient is that when we write:
```
given frac p;
invariant 0/1 < p && p < 1/1;
```
we get ` 0 < p && p < 1`  in the compiled file and again VerCors complains about type checking:
```
[debug] At Main.java:634: 
[debug] java.lang.AssertionError: assertion failed: Expected both operands to be of the same sort, but found Int (0) and Perm (p@12@03).
[debug] At Main.java:634: 
```

**Comment by niomaster** [comment]
In viper, the default permission operator is `/`. It prefers fraction-based division for permissions, but will cast to an int if so desired. The `\` operator forces integer division.

In vecors we don't have multiple operators for division, but I think we should. I would suggest leaving `a/b` as integer division, as that is default in all the languages we support, and making a new operator for fraction division. In particular, the `0/1` is probably rewritten by a jspec rule.

**Comment by niomaster** [comment]
For the new division operator, I set the type to `ZFraction`. There's two types in vercors, `ZFraction` and `Fraction`, of which `ZFraction` may be zero, and `Fraction` may not. A fraction division may very well contain variables, so it may reslut in zero. This results however in the value not being accepted by the `Fraction` type anymore.

What is the purpose of having the type distinction in vecors? I understand that it may be nice to have a type that signifies any valid permission, and a type that is more flexible separately, but I think we should just choose one. They are translated to the same perm type in viper anyway, equivalent to `ZFraction`.

**Comment by niomaster** [comment]
We decided we want to keep both. It's nice if you're able to specify both `given frac p`, so some non-zero permission, and a type that is there for expression we cannot immediately derive the type from, or situations where we do want to model zero permission. In almost all relevant cases we can derive whether the type should be `frac` or `zfrac`, by observing the case in which the numerator is a constant integer. In almost all other cases both sides of the division involve fractions (e.g. splitting another permission).

Finally, we would like for the conditions of frac to be actually generated correctly, as `frac` maps to the `Perm` type, which does permit 0. I'm not quite sure what the best approach is there.

**Comment by niomaster** [comment]
I would like a little help, because I'm encountering a failure in history/future stuff. We decided to introduce ADT's for zfrac and frac as such (I'll only reproduce `frac` here):

```
domain frac {
    function frac_val(a: frac): Perm

    axiom frac_bound {
        forall a: frac :: 0/1 < frac_val(a) && frac_val(a) <= 1/1
    }
}

function new_frac(x: Perm): frac
requires 0/1 < x && x <= 1/1
ensures frac_val(result) == x
```

Basically all frac's are in `(0; 1]` axiomatically, which the constructor ensures. In history/future `merge` and `split` are generated (I'll only reproduce merge here, but they probably have similar solutions):

```
method merge(diz: Ref, current_thread_id: Int, frac1: frac, proc1: Process, frac2: frac, proc2: Process)
  requires diz != null
  requires 0 <= current_thread_id
  requires acc(hist_idle(diz, frac1, proc1), write)
  requires acc(hist_idle(diz, frac2, proc2), write)
  ensures acc(hist_idle(diz, new_frac(frac_val(frac1) + frac_val(frac2)), p_merge(proc1, proc2)), write)
{
  inhale false
}
```

The failure then is `Precondition of function new_frac might not hold. Assertion frac_val(frac1) + frac_val(frac2) <= 1 / 1 might not hold.` We would need something like `requires frac_val(frac1) + frac_val(frac2) <= 1 / 1`, but since I don't quite understand what the methods should do, I'm asking here.

**Comment by wytseoortwijn** [comment]
Just curious, perhaps I missed it, but why is it decided to have a separate axiomatic domain for (z)fracs? Don't the built-in perms of Viper suffice?

**Comment by niomaster** [comment]
We wanted to have the conditions about (z)fracs automatically and it's quite difficult to generate conditions for that in general in nested data structures (arrays of fracs etc.)

**Comment by wytseoortwijn** [comment]
What they do is a bit technical and perhaps requires a little bit of background.

The two methods `split` and `merge` operate on processes, which are taken from an axiomatic domain `Process` of processes.

In the underlying logic of histories/futures, every process is paired with a fractional permission. We may for example write `Proc(P, pi)` for a process `P` that is paired with a fractional permission `pi`. (I think the current implementation uses the notation `Future(..)` instead of `Perm(..)` though, which should change at some point.)

The method `split` allows to "split" such a `Proc` predicate. More specifically, it allows to split `Proc(P1 || P2, pi1 + pi2)` into `Proc(P1, pi1) ** Proc(P2, pi2)` (where `||` is parallel composition; your earlier snippet uses the constructor `p_merge` for this).

The `merge` method does the opposite: it "merges" `Proc(P1, pi1) ** Proc(P2, pi2)` into `Proc(P1 || P2, pi1 + pi2)`.

So I think adding `requires frac_val(frac1) + frac_val(frac2) <= 1 / 1` would already fix it.

**Comment by niomaster** [comment]
Thanks for the detailed explanation!
