### ISSUE TITLE
Auto-format codebase?

### ISSUE THREAD

**Issue by pieter-bos** [utwente-fmt/vercors#330]
I'd like to consider again whether it is worth it to auto-format the codebase to some (yet to be decided) standard. 

Pros:
 - More consistent codebase
 - We can communicate a standard to contributors
 - No more merge conflicts because someone auto-formatted just one file

Cons:
 - Largely destroys blame history for files
 - Requires coordination such that it does not break merge compatibility for branches currently in development

**Comment by bobismijnnaam** [comment]
The blame history can be partially restored by telling git to ignore the revision where the autoformat happened (https://git-scm.com/docs/git-blame#Documentation/git-blame.txt---ignore-revltrevgt). Either that or a revision can be supplied to `git blame` such that `git blame` starts annotating from the given revision, which then also avoids code "tainted" by the auto-format.

I think making getting the blame history for older files a bit harder is worth it.

**Comment by OmerSakar** [comment]
One way to define a standard format would be a self-defined checkstyle file. 

It could be integrated with Travis CI such that the file is automatically checked against the standard. The checkstyle job should then be allowed to fail (if there is a checkstyle error/warning) so that other jobs can still continue.

With a checkstyle file and Travis CI, it could be said that a merge request which does not hold against the standard will not be merged. This way the standard could be enforced.

**Comment by niomaster** [comment]
To add to bob, that feature is qutie new (Git 2.23, e.g. I am on 2.17 currently). Also, I'm a lazy man, so I'd like the IntelliJ `Annotate' feature to keep working. However, I realized the current approach is roughly to auto-format the file whenever you're working on it, and that destroys the history anyway, so I'm leaning towards yes.

**Comment by bobismijnnaam** [comment]
Another format related thought I had: maybe the pass names should be standardized? E.g. java-check vs. java_resolve.

**Comment by pieter-bos** [comment]
Time sure keeps on marching huh:
* GitHub supports <https://github.blog/changelog/2022-03-24-ignore-commits-in-the-blame-view-beta/>
* My git is now 2.37.2, so we can probably safely use `blame.ignoreRevFile`
* The above option makes ignoring the appropriate revisions the default, so it also works in my IDE.
