### ISSUE TITLE
Variable named 'to' results in syntax error

### ISSUE THREAD

**Issue by Sophietje** [utwente-fmt/vercors#408]
I was trying to verify a program but ran into the problem "mismatched input 'to'". It seems like 'to' behaves like a reserved keyword even though I could not find any 'to' keyword in PVL. 

It can be reproduced with the following code snippet:
```
class Bla {
	int top;
	
	int foo(int to) {
		this.top = to;
	}
}
```

Trying to verify this program with the silicon backend will result in the following warnings:
```
[warning] ../Research/CaseStudyVerification/test-to-keyword.pvl, 4:13 mismatched input 'to' expecting {'\result', 'action', 'atomic', 'label', 'process', 'create', 'apply', 'use', 'destroy', 'split', 'merge', 'open', 'close', 'send', 'recv', 'from', '\current_thread', Identifier}
[warning] ../Research/CaseStudyVerification/test-to-keyword.pvl, 5:13 mismatched input 'to' expecting {'{', '(', 'unfolding', '?', '-', '*', '!', 'new', '[', 'this', 'null', 'true', 'false', 'current_thread', '\result', '\owner', 'id', '|', '[t:', '{t:', 'b{', 'b{t:', 'Value', 'HPerm', 'Perm', 'PointsTo', 'Hist', '\old', 'idle', 'running', 'head', 'tail', 'held', 'Some', 'action', 'atomic', 'label', 'option', 'string', 'process', 'int', 'boolean', 'zfrac', 'frac', 'resource', 'void', 'create', 'apply', 'use', 'destroy', 'split', 'merge', 'open', 'close', 'send', 'recv', 'from', '\unfolding', '\current_thread', '\sum', '\length', '\id', '\typeof', '\matrix', '\array', '\pointer', '\pointer_index', '\values', '\vcmp', '\vrep', '\msum', '\mcmp', '\mrep', 'Reducible', CONTAINER, Identifier, NUMBER}
encountered 2 syntax error(s) in ../Research/CaseStudyVerification/test-to-keyword.pvl
```

Does anyone have an idea why this might act as a reserved keyword? Can we remove it from the list of reserved keywords?

**Comment by niomaster** [comment]
It's lexed as part of a send statement (`send x to y`). Certainly we should allow it in the outer syntax of other languages, but I'm not sure whether we should allow it in PVL. any opinions?

**Comment by Sophietje** [comment]
Ah right, I forgot about the second part of the send statement.
As a user I'd prefer to be able to use 'to' as a variable name if it is not used in conjunction with send in PVL. However, if it's quite some work, then I'd say that we can better focus our efforts elsewhere and simply mention in the PVL syntax that 'to' is a reserved keyword.

**Comment by bobismijnnaam** [comment]
For PVL documenting it is probably best. Since it is a language keyword it's probably not good to allow it as a variable name (might break parsing...?).

In the case of Java I think it should be possible, as a company shouldn've have to rename their variables if they start using VerCors. But this leads to the problem where you cannot refer to the "to" variable in contracts, since in the verification grammar "to" is a reserved word. Maybe for these cases we can introduce an "escaping" operator ($? But personally I think something more verbose and less important is better, e.g. "\escape(to)"), so you can dip into the "reserved namespace" when it's needed and still keep the nice syntax for "send ... to ..." (I dislike backslashes everywhere. That's the other option, if adding an "escape operator" is not possible)
