### ISSUE TITLE
Generated viper code contains <.*>

### ISSUE THREAD

**Issue by Sophietje** [utwente-fmt/vercors#418]
When generating viper code, the method names contain stuff like "<Array<Cell<Edge>>>". This causes the viper plugin to complain about < and > (parse error). Therefore, it'd be great if we could remove < and > from the generated code.

**Comment by OmerSakar** [comment]
The issue seems to be that we create a `Method` object and include the name of a collection (such as a sequence or array) and do not check for any illegal characters.

I have found one quick fix, however, I do not know if this solves all issues. One method that generates new method names is `create_method_name` in `JavaEncoder`. We could do something like `return (prefix+res).replaceAll("([<>,])","_");` instead of just `return prefix + res`.

**Comment by OmerSakar** [comment]
After some more consideration, I think the best way is to replace the illegal characters when a new `Method` object is instantiated. That way we cannot have this issue in the future.

**Comment by bobismijnnaam** [comment]
It would be nice if in COL any name for a method was allowed (including #, $, //, 👍). Then it could be escaped/replaced if the backend doesn't like certain characters, and we can keep the debug output nice at the same time.

**Comment by niomaster** [comment]
As an aside, this is part of the consistency check that we are missing. See also #393

**Comment by bobismijnnaam** [comment]
As a quick test I added three lines of code in silver-class-reduction that replaces "<" and ">" with "$" in method & method invokations. This seems to work well for the few examples I've tried (they now parse instantly in vscode) but might not be enough for the general case.

I think we can implement this quick-fix and reopen this issue again if it ever resurfaces. But not sure if we need anything more complicated than this in the foreseeable future. I think at least for abstract predicate families we'll be fine (those contain '@', but I can extend the special-character-replacement code if needed). Maybe you have some thoughts on this w.r.t. c++ support @OmerSakar?
