### ISSUE TITLE
Scaling of predicates associates too wide

### ISSUE THREAD

**Issue by ArmborstL** [utwente-fmt/vercors#443]
If I have a predicate `state` and use it in one precondition for two method parameters in a scaled way (i.e. `requires [read]state(a) ** [read]state(b);`), then this causes an error "nested use of scaling". This can be prevented by introducing parentheses, i.e. `requires ([read]state(a)) ** ([read]state(b));`. However, even without parentheses the scaling should not associate across the `**`.

**Comment by niomaster** [comment]
This problem is non-trivial because the [java expression parser](https://github.com/utwente-fmt/vercors/blob/f6f45dc1717a99fb3b6df6fefb1de831d5e72b3d/parsers/lib/antlr4/Java7.g4#L510) relies heavily on the left-recursion precedence trick described [here](https://github.com/antlr/antlr4/blob/master/doc/left-recursion.md). I would expect that since the scaling occurs via the first "primary" alternative that binds most tightly, but clearly it does not. Maybe there is a nice solution, or maybe we should switch to the explicit syntax, as e.g. in the [PVL parser](https://github.com/utwente-fmt/vercors/blob/f6f45dc1717a99fb3b6df6fefb1de831d5e72b3d/parsers/src/main/antlr4/PVFull.g4#L52)
