### ISSUE TITLE
Barrier does not redistribute permissions

### ISSUE THREAD

**Issue by Safari1991** [utwente-fmt/vercors#448]
It seems that the implementation of barrier does not fully follow the logic. A barrier should only redistribute the available permissions and should not invent permissions, but in the tool the following is allowed:

barrier(threads){
requires (\forall* int i; i >= 0 && array.length; Perm(array[i], read);
ensures (\forall* int i; i >= 0 && array.length; Perm(array[i], write);
}

In this barrier, each thread has read permissions to all locations in the array as precondition and obtains write permission to all locations as postcondition. According to the logic we cannot invent permission in the barrier.

**Comment by bobismijnnaam** [comment]
As a preliminary check, we could check if plain implication holds between the requires and ensures. For example, for a barrier where every thread gets permission for an index from the next thread, and the permissions wrap around, we could emit the following method as a proof obligation:

```
class MyClass {
  int[] xs;

  context Perm(xs, read) ** xs != null;
  requires (\forall* int i = 0..xs.length; Perm(xs[i], write));
  ensures (\forall* int i = 0..xs.length;
      i == 0 
        ? Perm(xs[xs.length - 1], write) 
        : Perm(xs[i - 1], write)
        );
  void foo() {
    // No proof steps needed
  }
}
```

This currently does not verify because of #456, but the silver output verifies in vscode, so I think this can be good a starting point. This approach can also be implemented by emitting asserts around the barrier, or in a special method that checks all the barriers, but the idea is the same.

I think if we implement this, possibly some barriers that are actually correct will fail because additional proof steps are needed. So maybe we should start out with implementing this check as a warning, and when we make the implementation smarter or support user-supplied proof-steps we can make it an error.

**Comment by niomaster** [comment]
Is it really true that this is not checked? This piece of code seems to generate the check we want: https://github.com/utwente-fmt/vercors/blob/024836dbd4935ae1ed40a03d5acf2fc6f9a88e58/src/main/java/vct/col/rewrite/ParallelBlockEncoder.java#L172-L224

**Comment by bobismijnnaam** [comment]
I haven't checked the generation code properly, but the following seems problematic:
```
method barrier_check_2(diz: Ref, current_thread_id: Int)
  requires diz != null
  requires 0 <= current_thread_id
  requires 0 < |[0..1)|
  requires (forall tid: Int :: 0 <= tid && tid < 1 ==> acc(diz.field_C_array, wildcard))
  requires 0 < 1 ==> diz.field_C_array != VCTNone()
  requires (forall tid: Int, i: Int :: 0 <= tid && tid < 1 && (0 <= i && i < alen(getVCTOption1(diz.field_C_array))) ==> acc(loc(getVCTOption1(diz.field_C_array), i).Integer__item, wildcard))
  ensures 0 < |[0..1)|
  ensures (forall tid: Int :: 0 <= tid && tid < 1 ==> acc(diz.field_C_array, wildcard))
  ensures 0 < 1 ==> diz.field_C_array != VCTNone()
  ensures (forall tid: Int, i: Int :: 0 <= tid && tid < 1 && (0 <= i && i < alen(getVCTOption1(diz.field_C_array))) ==> acc(loc(getVCTOption1(diz.field_C_array), i).Integer__item, write))
{
  inhale false
}
```
I guess if we remove the `inhale false` we get at least basic checking. For complex barriers we should maybe consider the warning approach suggested earlier, or allow turning off generating the barrier check for specific barriers. The second option is better I think.

**Comment by bobismijnnaam** [comment]
With the right syntax, the barrier check is emitted.

Syntax for enabling the barrier check:

```java
barrier(name)
requires x;
ensures y;
{
 // No proof steps supplied;
}
```

Syntax for disabling the barrier check:

```java
barrier(thread) {
  requires x;
  ensures y;
}
```

We should probably only support the syntax of the first code block. For those who want to disable barrier checks, they can use `inhale false` to turn it off.

**Comment by Sophietje** [comment]
Note, don't forget to update the wiki pages to reflect any changes (such as [PVL Syntax Reference](https://github.com/utwente-fmt/vercors/wiki/PVL-Syntax-Reference))

**Comment by bobismijnnaam** [comment]
From @marieke73: Also, there is a spelling error in the encoding somewhere, as "parrallel" is emitted, which should be "parallel".

**Comment by niomaster** [comment]
there is no case in which the proof is skipped now.
