### ISSUE TITLE
Missing support for static variables initialisation in Java

### ISSUE THREAD

**Issue by raulmonti** [utwente-fmt/vercors#480]
Static final variables can't be initialise since something like this`public static final int CONST = 0;` gives an error about the current block being null. Static variables such as `public static int CONST = 0;` give the same error and the work around of initialising them in the constructor doesn't work either: I get a missing permissions error. First problem seems like support missing and bad error handling, and the second one looks like a bug?

**Comment by bobismijnnaam** [comment]
Completele support for static variables is difficult, as you would need a way to manage permissions for a static field (as far as I know). But for constants/immutable values we can implement something useful (since it would only require propagating read permissions). At the very least we can implement clear errors indicating we do not support it at the moment.

**Comment by niomaster** [comment]
See also some considerations on static methods conceptually #468

**Comment by niomaster** [comment]
This now doesn't crash, and final fields are at least known to vercors to be constant, although I believe we do not know the concrete value yet if it is a pure expression / constexpr.
