### ISSUE TITLE
Returning `null` in PVL

### ISSUE THREAD

**Issue by wytseoortwijn** [utwente-fmt/vercors#61]
One can currently not return `null` in a method body in PVL. This results in an exception with a message that looks like: `cannot declare variable __flatten_? of <<null>> type.` (with `?` some integer).

Minimal example program (in PVL):

```java
class List {
  List nothing() {
    return null;
  }
}
```

**Comment by wytseoortwijn** [comment]
Here a workaround would be:

```java
class List {
  List nothing() {
    List empty = null;
    return empty;
  }
}
```

**Comment by sjcjoosten** [comment]
Since this is now a type error in both cases (though the error is slightly different), we need to re-evaluate what to do: is this a bug or does the semantics of pvl not allow this? If we don't want to allow this, this is still a bug in Java (source code for that is the same, but in Java this is definitely allowed).

Any ideas wytse?

**Comment by niomaster** [comment]
I made a suggestion here: https://github.com/utwente-fmt/vercors/pull/186, though this makes no change to the semantics of PVL.
