### ISSUE TITLE
PVL constructor or contract grammar rule(s) misinterpreted.

### ISSUE THREAD

**Issue by OmerSakar** [utwente-fmt/vercors#614]
The following piece of code gives an error (the example might not make sense, it is about the problem in the grammar):

```
class Counter {
    int count;

	pure int notanewmethod() = 2;

	requires Perm(count, 1);
	ensures Perm(count, 1\2);
	ensures count == \old(count) + n;
        ensures notanewmethod();
	Counter(int n) {
		count = count + n;
	}
}
```

The error is:

```
=== demo1.pvl                      ===
   7 	ensures Perm(count, 1\2);
   8 	ensures count == \old(count) + n;
        [-------
   9     ensures notanewmethod();
         -------]
  10 	Counter(int n) {
  11 		count = count + n;
-----------------------------------------
  This identifier is reserved and cannot be declared.
=========================================
```

Since the constructor does not have a return type, the function call to `notanewmethod` gets interpreted as a method declaration and below it a constructor without a contract. Since `ensures` is a keyword, we get this error message. 

There is a very easy workaround, just add `** true` after the method call.

**Comment by ArmborstL** [comment]
Note: `ensures notanewmethod();` may be considered a type error if `notanewmethod` has type `int`. However, the error also occurs if we change its type to `boolean`, so this is not the issue here.

The issue seems to stem from [LangPVLParser.g4, Line 12](https://github.com/utwente-fmt/vercors/blob/dev/parsers/lib/antlr4/LangPVLParser.g4#L12): `methodDecl` is left of `constructor` and thus has higher precedence. Changing that order, i.e. turning the line into `clazMember : constructor | methodDecl | field;` (and adapting PVLtoCOL.scala accordingly), solves this issue. 
I'm a bit reluctant to push such a fix, since changing the parsing order may have unintended consequences in other cases. But running the test suite did not raise any problems, so we're probably fine.
