### ISSUE TITLE
Default constructor misses idle token

### ISSUE THREAD

**Issue by raulmonti** [utwente-fmt/vercors#646]
The default constructor for PVL classes misses to inhale and ensure the idle token in its contract, which is required to be able to fork instances of this class.

**Comment by bobismijnnaam** [comment]
This problem appears in examples/manual/fork.pvl, but because of the way the test is written, the error is hidden. Would you mind if I add this test to the branch where you are doing this? As it is also a nice test for your fix. (The test must be split up into three files, one for each testX method. test1 must succeed, but test2 and test3 must fail. This is because the "verdict" syntax is very loose and broken in the test suite...)

**Comment by raulmonti** [comment]
> This problem appears in examples/manual/fork.pvl, but because of the way the test is written, the error is hidden. Would you mind if I add this test to the branch where you are doing this? As it is also a nice test for your fix. (The test must be split up into three files, one for each testX method. test1 must succeed, but test2 and test3 must fail. This is because the "verdict" syntax is very loose and broken in the test suite...)

Yes! go ahead :) I will push a new commit after that, where I moved the is_runnable testing to the ASTClass instead of inlining it when building the default constructor.

**Comment by bobismijnnaam** [comment]
The change is applied on Petra's PR (#652), so you can pull that in once that is merged.
