### ISSUE TITLE
Staying on top of e.g. problem-fail cases

### ISSUE THREAD

**Issue by bobismijnnaam** [utwente-fmt/vercors#651]
We are lax towards actually fixing problematic cases in the problem-fail suite, and also towards keeping the failing problems in sync with vercor's features. For some tests (i.e. one that checks if `instanceof` is still supported), this is not problematic. But, for example, for verifythis related tests, or the leader elect test (which is one of the major examples of vercors process models), this is quite bad as these are useful tests both from the perspective of vercors as well as its users.

As it is impossible to solve every problem in the short term, it would be nice if we could, in the mean time, get a stronger guarantee that tests stay in sync with vercors, syntax and feature wise.

One example of where this happened is the leader elect program; it was removed from the test suite because of non-termination. Then some updates happened to vercors, and after that vercors did not even accept it syntactically anymore. Since nontermination is an issue on viper side, what we instead could have done is only skip the viper phase. That way we would've noticed when actual vercors syntax went out of sync with what is used in leader elect, and the person changing that could've fixed it at that time, instead of doing it later in an unrelated context.

My initial proposition would be to have several categories of tests:
- Tests that should behave as specified by the verdict in the file
- Tests that should get through all passes in vercors, except for the backend pass
- Tests that should parse and and typecheck
- Tests that should only parse

There could be another category of tests that do not even parse, but I'd say those are better kept track of as feature requests in issues or as "possible future projects" in the wiki or something.

My initial idea would be to implemented these modes through flags, and then have different test suites for each category (problem-skip-backend, problem-only-typecheck, problem-only-parse. Suggestions welcome), but we could also do it differently.

**Comment by Vescatur** [comment]
Those sound like good changes. I would also like to add some ideas.

These things sound like big changes to our test framework. Could we consider implementing these test inside scalatests? I think scalaTest has better integration with the ide and github actions. The scalaTest for example give a list of failing test inside the "files changed" page of github. In Intelij there is a button in the test file to run a test. For our test framework you would have to do a little configuration. 
I would say that all of these things are nice to have but are not a high priority. However since we want to make a big change 
I think it would be nice to incorporate these.

For ease of discussion I will number the categories

1. Tests that should behave as specified by the verdict in the file
2. Tests that should get through all passes in vercors, except for the backend pass
3. Tests that should parse and and typecheck
4. Tests that should only parse

I am in doubt of the value of the tests in 3 and 4. I think we should only use them if they are really required.

I think test 2 does add some value. Would it be possible to compare the end result with expect viper code? (Even though the viper code may be insufficient.) The benefit would be a better test however it would also come at the cost of maintenance. In case a change is required but still valid, one would need to change all of these tests. What is your opinion of it?

**Comment by bobismijnnaam** [comment]
After some discussion during the meeting we came to the conclusion that we would like to implement this. Following Ivan's categories, category 2 should definitely be implemented, and for category 3 we have to evaluate to see if we really have tests in problem-fail that need it. We don't think category 4 is necessary.

Re: using scalatest for the test suite, this should be a nice improvement w.r.t. standardization and integration, given that we can port over most of the features of the current custom testing framework. However it is slightly out of scope of this issue, so we leave it for later. Anyone who is interested in this can maybe reuse some work I did here: https://github.com/utwente-fmt/vercors/tree/refactor-testing-to-scalatest

Re: doing a diff on the viper output: might be workable, but for a test suite of vercors' size, we are not sure if it scales.
