### ISSUE TITLE
Converting integration tests to ScalaTest

### ISSUE THREAD

**Issue by Vescatur** [utwente-fmt/vercors#678]
I would like to explain my vision for converting to ScalaTest and how I am going to make it. Feedback is welcomed. 
-no test code in /src it should all be contained in the test folder. (In case it is necessary I will inject code using dependence injection)
-The test configuration should be moved from the example folder to a scalaTest class. (Otherwise I would need to build some automated conversion between example test to scalaTest. I think that is trying to build a test framework upon a test framework. I also think it adds some benefit of having configuration in code)
-I would like to use the output given to System because it less likely to change compared to the console output.
-It should be possible to specify which passes are run. The execution should be able to stop after verification or before viper. (This is the latest feature Bob made.)
-I am not sure whether I will do the following. Currently the test suite is too slow and big that I am not able to run it locally. It just takes an hour. For local use I would like to speed it up by using a Viper cache. It works as follows, after running a successful test the silver code will saved to a file. In a next run it will check whether the generated silver code equals the saved file. If that is the case it will skip Viper. The cache will not be saved to the repository. It is possible to have a cache in Github action but I have not decided whether I want to.
-The tests should be split among multiple computers for Github actions. I do not know how I will do this. I do not think it is a feature of ScalaTest.

How I am going to approach dependence injection:
Currently we do not use dependence injection. I will add it in two places. In System and in Main. 
-I would like to split Main into multiple classes each doing there own thing. I am currently thinking of one for options, one for passes and one which ties everything together.
-System is static so dependence injection can not be used. What I will do is give System a non static class which does all the work which System does. When testing the class will be replaced by test code.

**Comment by niomaster** [comment]
- can you explain a bit more about dependency injection and why we need it?
- re: moving configuration; I am not a big fan of this: after all the examples are also examples, so should be taken as (light) documentation to the user. It's not great that e.g. the expected verdict is then decoupled from the example. In any case, this information should be in a single place (so not both)
- we had a "do this pass list" at some point, but I don't think we should be able to pin the exact list of passes. Examples don't "know better" about future new passes than the new pass itself, so to speak.
- a viper cache is a great idea, but requires some finesse. Things I can think of right now: in the cache should be involved the version of z3, silver and silicon (or carbon), and we should consider that results of viper are not necessarily stable. Since probably only we work on unstable vercors examples, this can definitely be okay, but we should have a way to easily circumvent the cache for such cases.
- Otherwise I agree :)

**Comment by Vescatur** [comment]
We had a call about this issue. We choose to move the test configuration from examples to scalatest. The test configuration will be replace by a text comment. We will not use a list of passes in the test configuration. The test configuration will have an enum option to define whether it stops before viper or before passes. The viper cache will be more difficult then anticipated. I will investigate the feature in case there is a lot of time.

**Comment by bobismijnnaam** [comment]
By text configuration, you mean the "//::" blocks in each example?

Any idea already on how to split the test cases over computers? It would be nice to reduce the actions runtime in case our own cache is not usable.
