### ISSUE TITLE
Next viper release behaviour changes

### ISSUE THREAD

**Issue by bobismijnnaam** [utwente-fmt/vercors#724]
Next viper release will change some behaviour with regard to injectivity checks. In the current release, they added a flag `--checkInjectivity`, which, quoting Malte:

> if enabled, instructs Viper to check the injectivity of quantifier permission receivers *also upon inhaling*, where it is currently a free assumption.

In the next release, this will be the default.

We should check the test suite if any examples depend upon this unchecked behaviour. Quoting Malte again:

> a precondition such as
>
> ```
> requires forall i: Int :: 0 <= i && i < |xs| ==> acc(xs[i].f, 1/2)
> ```
>
> must then be strengthened to
>
> ```
> requires forall i: Int, j: Int ::
>   0 <= i && i < j && j < |xs| ==> xs[i] != xs[j]
> requires forall i: Int :: 0 <= i && i < |xs| ==> acc(xs[i].f, 1/2)
>```

**Comment by niomaster** [comment]
Note: this change does not yet solve https://github.com/utwente-fmt/vercors/issues/564, so permission-collapsing lemma's like 

```
axiom resource_independent_quant {
  (\forall* int tid; (tid \memberof {e1..e2}); (Perm(g1, p1)!tid))
  ==
  (e1<e2) ==> Perm(g1, p1*(e2-e1))
}
```

are still equally "wrong".

**Comment by niomaster** [comment]
Practically (in new VerCors) this just necessitates changing injectivity from "truth value" (for lack of a better term) to a well-formedness property. That is, it's currently the [reason](https://github.com/utwente-fmt/vercors/blob/ast/col/src/main/java/vct/col/origin/Blame.scala#L15-L17) for an [assertion](https://github.com/utwente-fmt/vercors/blob/ast/col/src/main/java/vct/col/origin/Blame.scala#L44-L47) being false, and now it must become an error unto itself like [DivByZero](https://github.com/utwente-fmt/vercors/blob/ast/col/src/main/java/vct/col/origin/Blame.scala#L103-L106).

I think it's most logical to then assign a `Blame[NotInjective]` to `Starall`. I think in the majority of cases we'll be able to inherit the blame from user code (when there's just a forall* specified), or it will never be non-injective (e.g. \values reasons over arrays, hence axiomatically injective). It does make #564 more pressing, since there assertions are automatically quantified over the thread ids, and it's not desirable to demand those are injective in the thread ids (e.g. `Perm(sharedState, read)`)

**Comment by ArmborstL** [comment]
After @bobismijnnaam ran the VerCors tests with the `--checkInjectivity` flag (https://github.com/utwente-fmt/vercors/actions/runs/1783962371), it seems like 8 tests failed:
- [AccessSubMatrixPass-silicon](https://github.com/utwente-fmt/vercors/tree/dev/examples/carp/access-sub-matrix-pass.c)
- [ArrayItemAccess-silicon](https://github.com/utwente-fmt/vercors/tree/dev/examples/basic/array-item-access.pvl)
- [demo3d-silicon](https://github.com/utwente-fmt/vercors/tree/dev/examples/demo/demo3d.pvl)
- [ForkJoinLoopPVL-silicon](https://github.com/utwente-fmt/vercors/tree/dev/examples/forkjoin/forkjoininforloop.pvl)
- Kadane-silicon (either the [1D](https://github.com/utwente-fmt/vercors/tree/dev/examples/verifythis/2017/other_attempts/kadane.java) or the [2D](https://github.com/utwente-fmt/vercors/tree/dev/examples/verifythis/2017/other_attempts/kadane2D.java))
- [SatCheck_Check-silicon](https://github.com/utwente-fmt/vercors/tree/dev/examples/basic/satcheck-check.pvl)
- [SeqItemAccess-silicon](https://github.com/utwente-fmt/vercors/tree/dev/examples/basic/seq-item-access.pvl)
- [ZeroSubMatrix-C-silicon](https://github.com/utwente-fmt/vercors/tree/dev/examples/carp/zero-sub-matrix.c)
It looks like most cases are about permissions of matrices (i.e. `\forall* ... Perm(m[i][j],p)`) or of fields in arrays/sequences (i.e. `\forall* ... Perm(mySeq[i].myField, p)`).
