### ISSUE TITLE
NoSuchElementException (None.get) related to inline predicates

### ISSUE THREAD

**Issue by JLedelay** [utwente-fmt/vercors#795]
Tested on dev branch (commit 0f69b58), with one change: 
vercors/rewrite/src/main/java/vct/col/rewrite/SimplifynestedQuantifiers.scala line 71-72 was changed to 
```
case Starall(_, triggers, _) if triggers.isEmpty => logger.warn(f"The binder '$e' contains no triggers")
case Forall(_, triggers, _) if triggers.isEmpty => logger.warn(f"The binder '$e' contains no triggers")
```
This change was applied to fix an earlier None.get related crash.

The following input program: 
```
class Main {

  void main() {
    int T = 10;
    Thread[] threads = new Thread[T];
    for (int i = 0; i < T; i++) {
      //@ assert i > 0 ==> threads[i-1].lockset();
    }
    
  }
}

final class Thread {

  C cs[];

  /*@
  inline resource lockset() = (\forall* int j = 0 .. cs.length; Value(cs[j]));
  @*/

}

class C {}
```
leads to the following error:
```
[WARN] Possible viper bug: silver AST does not reparse when printing as text
[WARN] { aloc(opt_get1(aloc(opt_get1(threads), i1 - 1).ref.cs), j).ref } is not a valid Trigger (vercors-7602473723624880258.sil@213.41--213.106)
[DEBUG] List(Verification aborted exceptionally (<no position>))
[ERROR] Viper has crashed: java.util.NoSuchElementException: None.get
```

Possibly related to [issue 789](https://github.com/utwente-fmt/vercors/issues/789)?

**Comment by niomaster** [comment]
It seems the (fairly new) SimplifyNestedQuantifiers pass generates an at that point correct trigger within the inline resource, i.e. `{: this.cs[j] :}`. This trigger is no longer valid after inlining, since the expression `{: threads[i-1].cs[j] :}` contains arithmetic (`i-1`). Interesting situation! :)

**Comment by niomaster** [comment]
Maybe this is a useful workaround for now:

```
//@ assert i > 0 ==> (\let Thread t = threads[i-1]; t.lockset());
```

**Comment by niomaster** [comment]
For posterity: inlined expressions (functions and predicates) now use `\let`s to evaluate the arguments and `given`s, and inlined statements use local variables to evaluate the arguments and `given`s, and out arguments and `yields`. In the case of methods the inlining was actually incorrect, since the evaluation of an assignment target (say `buf[i++]`) may have side effects, so it's incorrect to duplicate it.
