### ISSUE TITLE
Bags syntax

### ISSUE THREAD

**Issue by sjcjoosten** [utwente-fmt/vercors#85]
It should be figured out what all the syntax for bags is. This syntax should suffice to express that all elements in a list are precisely the elements in a bag.

**Comment by wytseoortwijn** [comment]
You can find some description on how to use bags in VerCors [here](https://github.com/utwente-fmt/vercors/wiki/Axiomatic-Data-Types).

**Comment by wytseoortwijn** [comment]
There are currently only two examples that use bags, which are:
- `examples/basic/CollectionTest.pvl`
- `examples/layers/Java6Lock.java` (although failing)

I would say that the Wiki gives a reasonably complete overview of the syntax of bags (partly due to the lack of examples). If a particular notation or operation appears to be missing I suggest we make a separate issue for this upon discovery.

@sjcjoosten what do you precisely mean by _"all elements in a list are precisely the elements in a bag"_? Do you have a concrete scenario?
