### ISSUE TITLE
Building on Windows

### ISSUE THREAD

**Issue by wytseoortwijn** [utwente-fmt/vercors#93]
VerCors does not seem to build under Windows (with e.g. Cygwin).

**Comment by HenkMulder** [comment]
Was fixed in #115, #124 and #145.

A new problem, after the latest Viper update is that the (unix) symbolic links in the Viper modules don't work on Windows. Causing the build to hang, since sbt can't load the Viper projects.
Creating symbolic links using ant or sbt is not an option, since Java does not support this on Windows.
